_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
acc_after_struct:
    value: 61.04
acc_after_unstruct:
    value: 58.01
acc_orig:
    value: 94.64
architecture:
    value: ResNet18_struct60_unstruct40
batch_size:
    value: 64
dataset:
    value: CIFAR-10
epochs:
    value: 10
learning_rate:
    value: 0.01
params_after_struct:
    value: 4580490
params_orig:
    value: 11173962
structured_ratio:
    value: 0.6
unstructured_ratio:
    value: 0.4
