_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
alpha:
    value: 0.8
k_bits:
    value: 8
pipeline:
    value: pruning_quantization_with_distillation
prune_finetune_epochs:
    value: 25
quant_finetune_epochs:
    value: 25
structured_ratio:
    value: 0.82
student:
    value: ResNet14_fact
teacher:
    value: ResNet16
temperature:
    value: 4
unstructured_ratio:
    value: 0.3
